//
//  BasicCleanModels.swift
//  projectDiscount
//
//  Created by MacDetail on 17/7/2568 BE.
//  Copyright (c) 2568 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BasicClean
{
  // MARK: Use cases
  
//  enum Something
//  {
//    struct Request
//    {
//    }
//    struct Response
//    {
//    }
//    struct ViewModel
//    {
//    }
//  }
    enum Hello {
        enum Request {
            struct SayHello {
                let name: String
            }
        }
        
        enum Response {
            struct Greeting {
                let message: String
            }
        }
        
        enum ViewModel {
            struct DisplayGreeting {
                let message: String
            }
        }
    }
}
