//
//  BasicCleanPresenter.swift
//  projectDiscount
//
//  Created by MacDetail on 17/7/2568 BE.
//  Copyright (c) 2568 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BasicCleanPresentationLogic
{
    func presentGreeting(response: BasicClean.Hello.Response.Greeting)
}

class BasicCleanPresenter: BasicCleanPresentationLogic
{
  weak var viewController: BasicCleanDisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: BasicClean.Hello.Response)
//  {
//    let viewModel = BasicClean.Hello.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
    
    
    func presentGreeting(response: BasicClean.Hello.Response.Greeting) {
        let viewModel = BasicClean.Hello.ViewModel.DisplayGreeting(message: response.message )
        viewController?.displayGreeting(viewModel: viewModel)
    }

}
