//
//  BasicCleanInteractor.swift
//  projectDiscount
//
//  Created by MacDetail on 17/7/2568 BE.
//  Copyright (c) 2568 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BasicCleanBusinessLogic
{
//  func doSomething(request: BasicClean.Hello.Request)
    func sayHello(request: BasicClean.Hello.Request.SayHello)
}

protocol BasicCleanDataStore
{
  //var name: String { get set }
}

class BasicCleanInteractor: BasicCleanBusinessLogic, BasicCleanDataStore
{
  var presenter: BasicCleanPresentationLogic?
  var worker: BasicCleanWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func sayHello(request: BasicClean.Hello.Request.SayHello) {
        let message = "Hello, \(request.name)"
        let response = BasicClean.Hello.Response.Greeting(message: message)
        presenter?.presentGreeting(response: response)
    }
//  func doSomething(request: BasicClean.Hello.Request)
//  {
//    worker = BasicCleanWorker()
//    worker?.doSomeWork()
//    
//      let response = BasicClean.Hello.Response.Greeting(message: "xxx")
//    presenter?.presentSomething(response: response)
//  }
}
